# Workflow derived from https://github.com/r-lib/actions/blob/master/.github/workflows/render-readme.yaml
# and https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/
# Workflow triggering derived from: https://stevenmortimer.com/running-github-actions-sequentially/
on:
  workflow_dispatch:
  push:
    paths:
      - 'README.Rmd'

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            rmarkdown
            
          needs: website
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
        
      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
          
      - name: Trigger pkgdown workflow
        if: success()
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: trigger-pkgdown-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
